### ISSUE TITLE
How to authenticate with jwt?

### ISSUE THREAD

**Issue by purefun** [MichalLytek/typegraphql-nestjs#10]
After learning some tutorials below,

- https://docs.nestjs.com/techniques/authentication
- https://typegraphql.com/docs/authorization.html
- https://github.com/MichalLytek/typegraphql-nestjs/#caveats

Still don't know how to integrate `typegraphql-nestjs` with jwt.

Could you make some examples? 
thanks in advance.

**Comment by MichalLytek** [comment]
You need to put decoded token or user into `context`, like here:
```ts
GraphQLModule.forRoot({
  context: ({ req }) => ({ req }),
});
```

You can experiment with `PassportModule` and `JwtModule` like in docs but you can use NestJS guards in that case.

Then in `authChecker` you have access to that context and declared roles, so you can put your business rules there.

**Comment by purefun** [comment]
Thank you for your immediate response. 
But the key is I don't know how to attach the authenticated user to `req` when using `TypeGraphQLModule.forRoot`. 😂

**Comment by MichalLytek** [comment]
You need to use some nest way to register a JWT HTTP middleware on `/graphql` path, so it will will parse the auth header token, verify and put decoded payload as `req.user`. 

In low level, basic way, you can create express app, then use `express-jwt` middleware and then make Nest App using your express app.

**Comment by purefun** [comment]
I saw the clue in the doc https://typegraphql.com/docs/authorization.html#recipes. 
Thank you for your helpful response again.
👍

**Comment by eloiqs** [comment]
@purefun Sorry for poking you through a closed issue, but could you give a high level description of the solution you implemented?

**Comment by chriszrc** [comment]
@MichalLytek does this mean we have to manually extend all of the auto generated resolvers to apply the `@Authorized()` decorator?

**Comment by MichalLytek** [comment]
@chriszrc https://prisma.typegraphql.com/docs/advanced/additional-decorators

**Comment by chriszrc** [comment]
@eloiqs @MichalLytek It would seem that an example of what is the recommended way to do this:

> You need to use some nest way to register a JWT HTTP middleware on /graphql path,

is needed. The examples use express-jwt, and I'm unsure how to register middleware on an arbitrary route in nestjs. But it looks like here:

```
@Module({
  imports: [
    TypeGraphQLModule.forRoot({
      driver: ApolloDriver,
      emitSchemaFile: true,
      authChecker,
      scalarsMap: [{ type: Date, scalar: GraphQLTimestamp }],
      context: ({ req }) => {
         //We could do extractTokenFromHeader and jwtService.verifyAsync right here and 
         //add req['user'] = payload;
         return { currentUser: req.user }
       },
    }),
    RecipeModule,
  ],
})
```

Is there any problem with that?
