### ISSUE TITLE
Problem with scoped providers

### ISSUE THREAD

**Issue by danielsantiago** [MichalLytek/typegraphql-nestjs#2]
When I try to use `@Injectable({ scope: Scope.REQUEST })` in my resolver I got the following error `RecipeResolver is marked as a scoped provider. Request and transient-scoped providers can't be used in combination with "get()" method. Please, use "resolve()" instead.`

The error point to this line:
https://github.com/MichalLytek/typegraphql-nestjs/blob/master/src/typegraphql-options.factory.ts#L58

It looks like for scoped providers we need to use `resolve()` instead of `get()`.
https://docs.nestjs.com/fundamentals/module-ref#resolving-scoped-providers

**Comment by MichalLytek** [comment]
@danielsantiago 
Thanks for the report!

I wonder whether `resolve()` works the same way for singleton scoped injectables?
So does `await injector.resolve(MyService) === await injector.resolve(MyService)`?

Or maybe there is some other way to read the injectable setting in the `typegraphql-options.factory` to properly translate TypeGraphQL's `.get()` calls into `.get()` or `.resolve()` from NestJS? 🤔

**Comment by MichalLytek** [comment]
> So does await injector.resolve(MyService) === await injector.resolve(MyService)?

I have checked and this is true. So I can safely use `.resolve()` but I need to add support for async container in the core package.

**Comment by MichalLytek** [comment]
Closing via 93fe52b 🔒 

@danielsantiago Please update to `v0.2.0` and let me know it if works for you 😉
