### ISSUE TITLE
Nest v8.0.0

### ISSUE THREAD

**Issue by lcanavesio** [MichalLytek/typegraphql-nestjs#24]
Hi @MichalLytek ! How are you? 

When i want to use typegraphql-nestjs in a new project nestjs 8.0.0 throws me dependency peer error

`npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.6.13" from typegraphql-nestjs@0.3.1
`

Possible solution update your package.json 
"@nestjs/common": "^7.6.13" to "@nestjs/common": "^8.0.0",
"@nestjs/core": "^7.6.13" to  "@nestjs/core": "^8.0.0",
 "@nestjs/graphql": "^7.9.10" to  "@nestjs/graphql": "^8.0.2"

**Comment by MichalLytek** [comment]
I will upgrade the deps and check compatibility, because some DI container internals might have changed in major release.

**Comment by lcanavesio** [comment]
Thanks @MichalLytek !

**Comment by MichalLytek** [comment]
Available in `typegraphql-nestjs@0.4.0` 🎉
