### ISSUE TITLE
Support apollo/federation@0.33.0

### ISSUE THREAD

**Issue by sgentile** [MichalLytek/typegraphql-nestjs#27]
getting the following errors:

```
npm i typegraphql-nestjs@0.4.0
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nestjs-prisma-graphql@0.0.1
npm ERR! Found: @apollo/federation@0.33.0
npm ERR! node_modules/@apollo/federation
npm ERR!   @apollo/federation@"^0.33.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @apollo/federation@"^0.29.0" from typegraphql-nestjs@0.4.0
npm ERR! node_modules/typegraphql-nestjs
npm ERR!   typegraphql-nestjs@"0.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/sgentile/.npm/eresolve-report.txt for a full report.
```

If I switch to 0.29, then it wants "@nestjs/graphql": "^8.0.2", but then it requires Conflicting peer dependency: apollo-server-core@2.25.2 so it cascades down etc...

These are the defaults right with latest NestJS:

```
"dependencies": {
        "@apollo/federation": "^0.33.0",
        "@nestjs/common": "^8.0.0",
        "@nestjs/config": "^1.0.1",
        "@nestjs/core": "^8.0.0",
        "@nestjs/graphql": "^9.0.5",
        "@nestjs/platform-express": "^8.0.0",
        "@nestjs/swagger": "^5.1.0",
        "@nestjs/terminus": "^8.0.1",
        "@prisma/client": "^3.1.1",
        "apollo-server-express": "^3.3.0",
        "graphql": "^15.6.0",
        "reflect-metadata": "^0.1.13",
        "rimraf": "^3.0.2",
        "rxjs": "^7.2.0",
        "ts-morph": "^12.0.0"
    },
```

**Comment by panworapol** [comment]
> getting the following errors:
> 
> ```
> npm i typegraphql-nestjs@0.4.0
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: nestjs-prisma-graphql@0.0.1
> npm ERR! Found: @apollo/federation@0.33.0
> npm ERR! node_modules/@apollo/federation
> npm ERR!   @apollo/federation@"^0.33.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @apollo/federation@"^0.29.0" from typegraphql-nestjs@0.4.0
> npm ERR! node_modules/typegraphql-nestjs
> npm ERR!   typegraphql-nestjs@"0.4.0" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /Users/sgentile/.npm/eresolve-report.txt for a full report.
> ```
> 
> If I switch to 0.29, then it wants "@nestjs/graphql": "^8.0.2", but then it requires Conflicting peer dependency: apollo-server-core@2.25.2 so it cascades down etc...
> 
> These are the defaults right with latest NestJS:
> 
> ```
> "dependencies": {
>         "@apollo/federation": "^0.33.0",
>         "@nestjs/common": "^8.0.0",
>         "@nestjs/config": "^1.0.1",
>         "@nestjs/core": "^8.0.0",
>         "@nestjs/graphql": "^9.0.5",
>         "@nestjs/platform-express": "^8.0.0",
>         "@nestjs/swagger": "^5.1.0",
>         "@nestjs/terminus": "^8.0.1",
>         "@prisma/client": "^3.1.1",
>         "apollo-server-express": "^3.3.0",
>         "graphql": "^15.6.0",
>         "reflect-metadata": "^0.1.13",
>         "rimraf": "^3.0.2",
>         "rxjs": "^7.2.0",
>         "ts-morph": "^12.0.0"
>     },
> ```

I stuck on this issues, same with you

Workaround downgrade @apollo/federation to 0.29.x to solve this but don't know how to fix that in another way

**Comment by MichalLytek** [comment]
Closing in favor of #32 🔒
