### ISSUE TITLE
Feature: Update @nestjs/graphql major version to 9

### ISSUE THREAD

**Issue by mattia-lau** [MichalLytek/typegraphql-nestjs#32]
Hi @MichalLytek,

as `graphql-transport-ws` is deprecate, can you please help to upgrade the `@nestjs/graphql` to version 9 ?

reference: https://github.com/nestjs/graphql/blob/30fc9075241bcd33b7d018f4afe9025f24218f1a/lib/interfaces/gql-module-options.interface.ts#L65

bootstrap:
```ts
  GraphQLModule.forRoot({
    subscriptions: {
      'graphql-ws': true
    }
  })
```

**Comment by RubtsovAV** [comment]
Do we have workaround for now? I can't install this package with nest 9

**Comment by MichalLytek** [comment]
I have a WIP on my local branch, will try to publish it this week.

**Comment by RubtsovAV** [comment]
> I have a WIP on my local branch, will try to publish it this week.

That's really awesome. I want to persuade it work for my new local project and I started it from scratch. And would be grateful for any help, can I somehow launch this using changes in package.json?

**Comment by RubtsovAV** [comment]
OK. I used the `--force` option and seems like everything works well

**Comment by MichalLytek** [comment]
Closing in favor of #32 🔒
