### ISSUE TITLE
Support for @nestjs/graphql major version 10

### ISSUE THREAD

**Issue by GlCap** [MichalLytek/typegraphql-nestjs#37]
Hello, I have been using your amazing libraries for some years now.

Recently nestjs released a new version of their graphql implementation which breaks quite a lot of things.

As was recently brought up in PR #32 `graphql-transport-ws` is officially deprecated and `fastify` version 3 is not compatible with @nestjs/graphql version 8 which is the latest officially supported version of this package.

Anyway it is somehow currently possible to use this package with @nestjs/graphql version 9 to use `graphql-ws` as I have been doing in my projects.

As I need this package for my current projects, for the time being I forked this repo and updated the dependencies and integration myself. (https://github.com/GlCap/typegraphql-nestjs)

Just wanted to let you know, I am willing to publish a PR with my fork. However I have no need for the federation module, and honestly I have no idea how to implement an integration for it, as I never even used GraphQL Federation myself.

Thanks for your time.

**Comment by MichalLytek** [comment]
😅 I haven't finished upgrading for the v8 and now it's even v10 🤯 

Will take a look at your fork, maybe it won't be so hard to upgrade. 
But first, TypeGraphQL v2.0 has to be published, glad you've found a workaround by yourself 🙌

**Comment by Borales** [comment]
@MichalLytek hi! is there any update on this? I understand you might be busy with some other work, but maybe you could give some approx timeframe for the compatible version with apollo gateway (there's already 2.x version) and nestjs (10.x)? 

thank you

**Comment by MichalLytek** [comment]
Closing as done in 3fc0038 🔒 
Will publish new version on npm soon 🚀
