### ISSUE TITLE
Apollo plugins

### ISSUE THREAD

**Issue by alegold** [MichalLytek/typegraphql-nestjs#56]
With `TypeGraphQLModule.forRootAsync` or `TypeGraphQLModule.forRoot`,  and using ApolloDriver, how could I include Apollo plugins?

Example:
```
import { ApolloServerPluginCacheControl } from '@apollo/server/plugin/cacheControl';
import { ApolloServerPluginLandingPageLocalDefault } from '@apollo/server/plugin/landingPage/default';
```

https://www.apollographql.com/docs/apollo-server/api/plugin/cache-control/
https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/

**Comment by MichalLytek** [comment]
In a same way like in NestJS?

**Comment by alegold** [comment]
Yes, like NestJs. With buildSchema, would it be possible?

**Comment by MichalLytek** [comment]
I guess it's a build schema, not build a server, so should work? Have you tried before asking? What's not working?

**Comment by alegold** [comment]
Apologies for the delay. The question would be how to import Apollo plugins when using the typographql-nestjs package? And with type-graphql package, is it possible?

**Comment by MichalLytek** [comment]
> how to import Apollo plugins when using the typographql-nestjs package

The same way like with the standard graphql nestjs package I guess

> And with type-graphql package, is it possible?

Just put them in apollo server configuration, right? TypeGraphQL is a schema builder, not a graphql server.

**Comment by alegold** [comment]
Thank you very much for the clarifications.
