### ISSUE TITLE
How do you create an inline field resolver that knows how to call into a grpc service?

### ISSUE THREAD

**Issue by felipellrocha** [MichalLytek/typegraphql-nestjs#6]
Hey. Title is pretty descriptive. Love this library because it solves a real pain point, I think TypeGraphql is much better than nest's implementation of code-first graphql. But, you mention using inline field resolves in the readme, but I'm not sure how to use it.

**Comment by MichalLytek** [comment]
As stated in docs:
https://typegraphql.com/docs/resolvers.html#field-resolvers

> For simple resolvers like averageRating or deprecated fields that behave like aliases, you can create field resolvers inline in the object type class definition
> However, if the code is more complicated and has side effects (i.e. api calls, fetching data from a databases), a resolver class method should be used instead. This way we can leverage the dependency injection mechanism, which is really helpful in testing

So if your field resolver does something more complex and requires injecting things, use resolver's field resolvers 😉

**Comment by felipellrocha** [comment]
Ah makes sense! :) Thanks for the help!
